### ISSUE TITLE
Enter should log in/add link on the panel

### ISSUE THREAD

**Issue by randomairborne** [randomairborne/SimpleShortener#21]

**Comment by tazz4843** [comment]
attempted fix in 9be73bad895b7f82cd56b1dadcb785273149054d, untested as i have no instances to test against

**Comment by randomairborne** [comment]
Fixed in https://github.com/randomairborne/SimpleShortener/pull/20/commits/9e4f9bfa498cd4cc80a1ebfbdc12be93853f1d9a
